URL_SERVICE: http://0.0.0.0:6198
HEADERS:
  "username": "lsun"
  "apikey": "defaultapikey"
  "channel": "server"
  "targetservice": "assingment"
  "X-Request-ID": "6789"
  "content-type": "application/json"  