components:
  schemas:
    Body_add_user_ASSIGNMENT_api_v1_user_add_post:
      properties:
        age:
          title: Age
          type: string
        file:
          format: binary
          title: File
          type: string
        firstname:
          default: ''
          title: Firstname
          type: string
        lastname:
          default: ''
          title: Lastname
          type: string
        nid:
          title: Nid
          type: string
        username:
          title: Username
          type: string
      required:
      - username
      - age
      - nid
      - file
      title: Body_add_user_ASSIGNMENT_api_v1_user_add_post
      type: object
    Body_update_user_ASSIGNMENT_api_v1_user_update__id__put:
      properties:
        age:
          title: Age
          type: string
        file:
          format: binary
          title: File
          type: string
        firstname:
          default: ''
          title: Firstname
          type: string
        lastname:
          default: ''
          title: Lastname
          type: string
        nid:
          title: Nid
          type: string
        username:
          title: Username
          type: string
      required:
      - username
      - age
      - nid
      - file
      title: Body_update_user_ASSIGNMENT_api_v1_user_update__id__put
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    UpdateConf:
      properties:
        conf_name:
          title: Conf Name
          type: string
        conf_value:
          title: Conf Value
          type: string
      title: UpdateConf
      type: object
    Users:
      properties:
        age:
          title: Age
          type: string
        firstname:
          default: ''
          title: Firstname
          type: string
        id:
          title: Id
          type: integer
        image:
          default: ''
          title: Image
          type: string
        lastname:
          default: ''
          title: Lastname
          type: string
        nid:
          title: Nid
          type: string
        username:
          title: Username
          type: string
      required:
      - username
      - age
      - nid
      title: Users
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    vm_response:
      properties:
        code:
          title: Code
          type: string
        data:
          title: Data
          type: object
        message:
          title: Message
          type: string
        status:
          title: Status
          type: boolean
      required:
      - status
      - message
      - code
      title: vm_response
      type: object
    vm_response_base:
      properties:
        code:
          default: ''
          title: Code
          type: string
        data:
          title: Data
          type: object
        message:
          default: ''
          title: Message
          type: string
        status:
          default: false
          title: Status
          type: boolean
      title: vm_response_base
      type: object
    vm_up:
      properties:
        password:
          title: Password
          type: string
        username:
          title: Username
          type: string
      required:
      - username
      - password
      title: vm_up
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /ASSIGNMENT/api/v1/check-api:
    get:
      operationId: check_api_ASSIGNMENT_api_v1_check_api_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Check Api
      tags:
      - CHECK
  /ASSIGNMENT/api/v1/check-oracle-db-connection:
    get:
      operationId: check_oracle_db_connection_ASSIGNMENT_api_v1_check_oracle_db_connection_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Check Oracle Db Connection
      tags:
      - CHECK ORACLE DB CONNECTION
  /ASSIGNMENT/api/v1/check-protected:
    get:
      operationId: protected_ASSIGNMENT_api_v1_check_protected_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Protected
      tags:
      - CHECK
  /ASSIGNMENT/api/v1/get-request-from-myself:
    get:
      operationId: get_request_from_myself_ASSIGNMENT_api_v1_get_request_from_myself_get
      parameters:
      - in: query
        name: p1
        required: true
        schema:
          title: P1
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Request From Myself
      tags:
      - GET REQUEST FROM MYSELF
  /ASSIGNMENT/api/v1/imb/update-conf:
    post:
      operationId: update_conf_ASSIGNMENT_api_v1_imb_update_conf_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConf'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Conf
      tags:
      - UPDATE CONF
  /ASSIGNMENT/api/v1/imb/update-log-level:
    post:
      operationId: update_log_level_ASSIGNMENT_api_v1_imb_update_log_level_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConf'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Log Level
      tags:
      - UPDATE LOG LEVEL
  /ASSIGNMENT/api/v1/load-and-test-model:
    get:
      operationId: load_and_test_model_ASSIGNMENT_api_v1_load_and_test_model_get
      parameters:
      - in: query
        name: my_image
        required: true
        schema:
          title: My Image
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Load And Test Model
      tags:
      - DEEP LEARNING
  /ASSIGNMENT/api/v1/load-and-test-model-by-index:
    get:
      operationId: load_and_test_model_by_index_ASSIGNMENT_api_v1_load_and_test_model_by_index_get
      parameters:
      - in: query
        name: index
        required: true
        schema:
          title: Index
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Load And Test Model By Index
      tags:
      - DEEP LEARNING
  /ASSIGNMENT/api/v1/raise-exception:
    get:
      operationId: raise_exception_ASSIGNMENT_api_v1_raise_exception_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Raise Exception
      tags:
      - EXCEPTION
  /ASSIGNMENT/api/v1/send-request-to-myself:
    get:
      operationId: send_request_to_myself_ASSIGNMENT_api_v1_send_request_to_myself_get
      parameters:
      - in: query
        name: p1
        required: true
        schema:
          title: P1
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Send Request To Myself
      tags:
      - SEND REQUEST TO MYSELF
  /ASSIGNMENT/api/v1/test-accuracy-for-range-of-data:
    get:
      operationId: test_accuracy_for_range_of_data_ASSIGNMENT_api_v1_test_accuracy_for_range_of_data_get
      parameters:
      - in: query
        name: idx1
        required: true
        schema:
          title: Idx1
          type: integer
      - in: query
        name: idx2
        required: true
        schema:
          title: Idx2
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Test Accuracy For Range Of Data
      tags:
      - DEEP LEARNING
  /ASSIGNMENT/api/v1/train-and-save-model:
    get:
      operationId: train_and_save_model_ASSIGNMENT_api_v1_train_and_save_model_get
      parameters:
      - in: query
        name: num_iterations
        required: false
        schema:
          default: 2000
          title: Num Iterations
          type: integer
      - in: query
        name: learning_rate
        required: false
        schema:
          default: 0.005
          title: Learning Rate
          type: number
      - in: query
        name: print_cost
        required: false
        schema:
          default: true
          title: Print Cost
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Train And Save Model
      tags:
      - DEEP LEARNING
  /ASSIGNMENT/api/v1/user/add:
    post:
      operationId: add_user_ASSIGNMENT_api_v1_user_add_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_add_user_ASSIGNMENT_api_v1_user_add_post'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vm_response_base'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add User
      tags:
      - USERS
  /ASSIGNMENT/api/v1/user/delete/{id}:
    delete:
      operationId: delete_user_ASSIGNMENT_api_v1_user_delete__id__delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          title: Id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vm_response_base'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete User
      tags:
      - USERS
  /ASSIGNMENT/api/v1/user/get:
    get:
      operationId: get_user_ASSIGNMENT_api_v1_user_get_get
      parameters:
      - in: query
        name: skip
        required: false
        schema:
          default: 0
          title: Skip
          type: integer
      - in: query
        name: limit
        required: false
        schema:
          default: 1000
          title: Limit
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Users'
                title: Response Get User Forexample Api V1 User Get Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get User
      tags:
      - USERS
  /ASSIGNMENT/api/v1/user/update/{id}:
    put:
      operationId: update_user_ASSIGNMENT_api_v1_user_update__id__put
      parameters:
      - in: path
        name: id
        required: true
        schema:
          title: Id
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_update_user_ASSIGNMENT_api_v1_user_update__id__put'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vm_response_base'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update User
      tags:
      - USERS
  /ASSIGNMENT/api/v1/users/login:
    post:
      operationId: login_ASSIGNMENT_api_v1_users_login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vm_up'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vm_response'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Login
      tags:
      - USERS
  /ASSIGNMENT/api/v1/users/refresh:
    post:
      description: 'The jwt_refresh_token_required() function insures a valid refresh

        token is present in the request before running any code below that function.

        we can use the get_jwt_subject() function to get the subject of the refresh

        token, and use the create_access_token() function again to make a new access
        token'
      operationId: refresh_ASSIGNMENT_api_v1_users_refresh_post
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vm_response'
          description: Successful Response
      summary: Refresh
      tags:
      - USERS
